spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/hotel?characterEncoding=UTF-8
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8
  jpa:
    properties:
      hibernate:
#        current_session_context_class: thread
        enable_lazy_load_no_trans: true
        jdbc:
          batch_size: 100
    open-in-view: false
#    hibernate:
#      naming:
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

mybatis-plus:
  global-config:
    db-config:
      table-underline: false
  configuration:
    map-underscore-to-camel-case: true


custom:
  reserve:
    ahead-limit: 15
