spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel?serverTimezone=CTT&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  jackson:
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:dataImpl/*/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
