spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel?serverTimezone=CTT&characterEncoding=UTF-8
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  jackson:
    time-zone: GMT+8
  profiles:
    active: dev

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
