spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/hotel?characterEncoding=UTF-8
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 100
    open-in-view: false

mybatis-plus:
  global-config:
    db-config:
      table-underline: false
  configuration:
    map-underscore-to-camel-case: true
