const getters = {
    //user
    availableRoomList: state => state.user.availableRoomList,
    creditTrans: state => state.user.creditTrans,
    addUserInfoVisible: state => state.user.addUserInfoVisible,
    captchaParams: state => state.user.captchaParams,
    token: state => state.user.token,
    orderDetailVisible: state => state.user.orderDetailVisible,
    userId: state => state.user.userId,
    userInfo: state => state.user.userInfo,
    userInfoList: state => state.user.userInfoList,
    modifyUserInfoListVisible: state => state.user.modifyUserInfoListVisible,
    modifyPasswordVisible: state => state.user.modifyPasswordVisible,
    currentPersonId: state => state.user.currentPersonId,
    currentPersonInfo: state => state.user.currentPersonInfo,
    evaluateOrdersVisible: state => state.user.evaluateOrdersVisible,
    availableOrderList: state => state.user.availableOrderList,
    //hotel
    manageHotelVisible: state => state.hotel.manageHotelVisible,
    current: state => state.hotel.current,
    upgradeToVIPVisible: state => state.user.upgradeToVIPVisible,
    userOrderList: state => state.user.userOrderList,
    hotelListLoading: state => state.hotel.hotelListLoading,
    hotelList: state => state.hotel.hotelList,
    personList: state => state.user.personList,
    currentHotelInfo: state => state.hotel.currentHotelInfo,
    currentHotelId: state => state.hotel.currentHotelId,
    orderModalVisible: state => state.hotel.orderModalVisible,
    currentOrderRoom: state => state.hotel.currentOrderRoom,
    orderMatchCouponList: state => state.hotel.orderMatchCouponList,
    announcementVisible: state => state.hotel.announcementVisible,
    commentList: state => state.hotel.commentList,
    orderSuccess: state => state.hotel.orderSuccess,
    //admin
    unboundHotelList: state => state.admin.unboundHotelList,
    marketerList: state => state.admin.marketerList,
    hotelManagerId: state => state.admin.hotelManagerId,
    managerList: state => state.admin.managerList,
    addManagerModalVisible: state => state.admin.addManagerModalVisible,
    addManagerParams: state => state.admin.addManagerParams,
    addMarketerModalVisible: state => state.admin.addMarketerModalVisible,
    addHotelToManagerVisible: state => state.admin.addHotelToManagerVisible,
    //hotelManager
    roomList: state => state.hotelManager.roomList,
    hotelListMatchManager: state => state.hotelManager.hotelListMatchManager,
    orderListMatchManager: state => state.hotelManager.orderListMatchManager,
    orderList: state => state.hotelManager.orderList,
    addHotelModalVisible: state => state.hotelManager.addHotelModalVisible,
    addRoomModalVisible: state => state.hotelManager.addRoomModalVisible,
    couponVisible: state => state.hotelManager.couponVisible,
    addCouponVisible: state => state.hotelManager.addCouponVisible,
    activeHotelId: state => state.hotelManager.activeHotelId,
    couponList: state => state.hotelManager.couponList,
    managerOrderDetailVisible: state => state.hotelManager.managerOrderDetailVisible,
    allRoomModalVisible: state => state.hotelManager.allRoomModalVisible,
    //marketer
    allPlatformCouponList: state => state.marketer.allPlatformCouponList,
    addPlatformCouponModalVisible: state => state.marketer.addPlatformCouponModalVisible,
};

export default getters;
